import MoonshotLayout from '@/components/MoonshotLayout';

const MoonshotNadi = () => {
	return (
		<MoonshotLayout
			title="Nationaal Agentschap voor Disruptieve Innovatie (NADI)"
			heroEyebrow="Onze visie op NADI"
		>
			<p>Nederland heeft een innovatieprobleem dat we niet willen zien. Onze universiteiten staan in de wereldtop, onze onderzoekers publiceren baanbrekende studies en toch blijven we achter als het gaat om het omzetten van kennis naar wereldveranderende doorbraken.</p>
			<p>Doorbraken die onmisbaar zijn voor het oplossen van de problemen waarmee we te maken hebben. Het stikstofprobleem vraagt om definitieve oplossingen, niet om compromissen. Huizen moeten in weken gebouwd worden, niet in jaren. Ons land moet klimaatbestendig worden voor de volgende eeuw, en een gezonde economie heeft constant innovatie nodig.</p>
			<p>Het antwoord ligt in een organisatie die Nederland nog niet heeft: een instituut dat bewust ‘onmogelijke’ doorbraken organiseert. Het internet, GPS, touchscreens in je telefoon en het mRNA-vaccin dat miljoenen levens redde: allemaal innovaties van dezelfde Amerikaanse organisatie, DARPA.</p>
			<p>Demissionair minister Vincent Karremans (Economische Zaken, VVD) kondigde onlangs aan te verkennen hoe Nederland een vergelijkbaar instituut kan oprichten: het Nationaal Agentschap voor Disruptieve Innovatie (NADI). In potentie is dit het meest ambitieuze Nederlandse research-and-development-initiatief in decennia.</p>
			<h2 className="font-space-grotesk text-2xl font-semibold text-slate-900">Grootste uitdagingen</h2>
			<p>Helaas kan een demissionair minister alleen een verkenning doen. Het is aan het volgende kabinet om de plannen door te zetten. Laten we vurig hopen dat het dat doet. Want als we dit goed doen, kunnen we aan de basis staan van doorbraken die de grootste uitdagingen van onze tijd oplossen.</p>
			<p>Maar om het NADI echt te laten slagen, moeten we wél bereid zijn een aantal dingen on-Nederlands te doen. Het Amerikaanse Darpa inspireerde al vergelijkbare organisaties in onder meer Duitsland (Sprind) en Engeland (ARIA). Zij keken goed naar wat Darpa zo’n succes heeft gemaakt. Dat geheim zit niet in het geld. Het budget van deze organisaties, zoals ARIA met 200 miljoen euro per jaar en Darpa met 4 miljard euro per jaar, is bescheiden vergeleken met wat Big Tech per jaar uitgeeft aan onderzoek en ontwikkeling (Amazon 75 miljard euro, Google 42 miljard, Facebook 38 miljard).</p>
			<p>Het geheim zit in de organisatie: kleine teams met briljante programmamanagers die als ‘mini-ceo’ voor vijf jaar de vrijheid krijgen om schijnbaar onmogelijke ideeën te realiseren. Geen commissies, eindeloos overleg of bureaucratie, maar een extreem ambitieuze missie, een zak geld en complete vrijheid.</p>
			<p>Ze zoeken allemaal naar potentieel grootse ideeën. Projecten die fantastisch zijn als ze lukken, ook al lijken ze nu nog onmogelijk. Ze organiseren onder andere wedstrijden waarbij externe teams worden uitgedaagd met een waanzinnig doel. Zo daagde Darpa in 2004 teams uit om met zelfrijdende auto’s door de woestijn te rijden. De winnaars kregen miljoenen om door te ontwikkelen en een uitdagender parcours aan te gaan.</p>
			<p>Het resultaat: de denkkracht van individuele topwetenschappers en ingenieurs werd samengebracht voor een gemeenschappelijke missie. Individuele puzzelstukjes zoals geavanceerde sensoren en slimme algoritmen, die anders her en der zouden verstoffen op een plank, werden samengebracht voor een inspirerend product dat liet zien dat sciencefiction geen fictie meer is (Google rijdt al meer dan 1 miljoen taxiritten per maand zonder chauffeur).</p>
			<h2 className="font-space-grotesk text-2xl font-semibold text-slate-900">Nieuwe golven</h2>
			<p>Dat is ook het moment dat investeerders geïnteresseerd raken en start-ups ontstaan. Ze zien een nieuwe ‘golf’ opkomen, zoals eerder met het internet, de smartphone en AI.</p>
			<p>Het doel is dan ook om nieuwe golven te creëren waar anderen op kunnen surfen. Zo investeerde Darpa 15 miljoen euro in zijn zelfrijdende-auto-wedstrijd. Het geld ging naar teams van universiteiten, bedrijven en onderzoeksinstellingen. Kleine teams die, gesteund door investeerders, later uitgroeiden tot miljardenbedrijven. Dat aanzuigende effect, waarbij publiek geld een veelvoud aan privaat kapitaal aantrekt, is de heilige graal van innovatiebeleid.</p>
			<p>In het voorstel van minister Karremans blijkt duidelijk dat er al goed naar buitenlandse voorbeelden gekeken is. Er komen kort wat eigenschappen voorbij waaraan NADI moet voldoen, zoals de zelfstandigheid van de organisatie en de autonomie van de teams. Mocht er echter een andere minister komen, dan moeten we waken voor typisch Nederlandse valkuilen die van NADI een verspilling van belastinggeld zouden maken.</p>
			<p>Ten eerste moet NADI niet te klein denken. Nooit kwam verandering van mensen met een houding van ‘doe maar gewoon, dan doe je al gek genoeg’. De succesvolle projecten bij Darpa, ARIA en Sprind resulteren niet in een enkel product of bedrijf, maar in een geheel nieuwe industrie. Het leiderschap wordt afgerekend op hoe groot zijn ideeën zijn, niet op de haalbaarheid. We moeten extreem ambitieus zijn. Klinkt het realistisch? Dan mikken we te laag.</p>
			<p>Ten tweede moeten we wars zijn van faalangst, en de neiging tot risicomijden negeren. In Nederland is elk mislukt project een politiek schandaal. We zijn daardoor steeds meer mechanismen gaan uitvinden om risico’s te beperken, zeker bij technische projecten. Die duren daardoor langer en zijn kostbaarder, terwijl er technisch zelden echte onzekerheden zijn.</p>
			<p>Bij de zeer ambitieuze NADI-projecten, die veel meer onzekerheden kennen, moet de reflex niet zijn om de risico’s in te perken, maar om mislukkingen te omarmen. Een ontploffende raket moet resulteren in luid applaus. Zonder spectaculaire mislukkingen ook geen spectaculaire successen. ARIA viert mislukkingen en gaat ervan uit dat zeven van de tien projecten falen. Dat is oké, zolang de overige drie projecten de wereld veranderen.</p>
			<p>Bovendien, als je ambitie hoog genoeg ligt, dan hebben ook gefaalde projecten een positieve impact op de industrie door de lessen die worden geleerd. Bij de eerste zelfrijdende-auto-race in de woestijn haalde niemand de finish. Het lukte ARIA niet om efficiënt biobrandstoffen op basis van algen te ontwikkelen. Maar dat project legde wel de basis van productie van eiwitten voor voeding, en nieuwe medicijnen.</p>
			<h2 className="font-space-grotesk text-2xl font-semibold text-slate-900">Risico's inperken</h2>
			<p>Ten derde moet NADI zorgen dat het niet de verkeerde leiders kiest. In Nederland staan vaak oud-politici, ambtenaren of bankiers aan het roer van publieke organisaties. Laten dit nu net mensen zijn die hun hele carrière hebben geleerd om risico’s in te perken. Bovendien hebben ze zelden leiding gegeven aan organisaties die disruptieve technologieën ontwikkelden en missen ze een fundamentele technische achtergrond.</p>
			<p>Ilan Gur, de topman van ARIA, is gepromoveerd in de technische materiaalkunde en heeft bedrijven opgericht in Silicon Valley. Het bestuur bestaat uit topwetenschappers en -ondernemers. NADI heeft leiders nodig die, net als Gur, technische diepgang combineren met ondernemerservaring en oog voor de publieke zaak.</p>
			<p>Ten vierde: onderdruk de reflex om consensus te zoeken, die bij elke investering de kop op zal steken. Zorgvuldige afweging van belangen is waardevol, maar niet bij een zoektocht naar disruptieve ideeën. Organisaties als Darpa zoeken naar ideeën waar sommigen zeer enthousiast over zijn, maar anderen niet, en stimuleren inbreng vanuit vele verschillende hoeken. Als er consensus is dat iets een goed idee is, dan zal de markt het wel oppakken.</p>
			<p>En als laatste mag er niet getornd worden aan de autonomie van NADI. Het is lastig aan een breed publiek uit te leggen dat ons belastinggeld gaat naar ideeën die voor velen klinken als sprookjes. Bovendien mislukken de meeste projecten. Om de vrijheid te hebben om toch door te zetten, moet de organisatie op zichzelf staan en zo veel mogelijk autonomie hebben.</p>
			<p>Dat betekent: geen vinger in de pap voor Invest-NL, TNO en ministeries. In het VK is ARIA zelfs vrijgesteld van het Britse equivalent van de Wet open overheid (Woo). Het toezicht op het verduisteren van belastinggeld is beperkt tot het hoognodige.</p>
			<h2 className="font-space-grotesk text-2xl font-semibold text-slate-900">Toptalent aantrekken</h2>
			<p>We moeten ook van de daken schreeuwen over NADI. Niet te calvinistisch zijn. Elk groots project heeft per definitie een fantastisch verhaal: een toekomstvisie die eenieder kan inspireren. Het verhaal vertellen zal het draagvlak vergroten en toptalent aantrekken.</p>
			<p>Sceptici zullen zeggen dat een dergelijk initiatief niet bij Nederland past. Maar Nederland kan dit. We hebben de kennis en het geld. We hebben het zelfs al eens gedaan met de Deltawerken: bedreigd door het water richtten we een aparte organisatie op, gaven deze een schijnbaar onmogelijke opdracht én de vrijheid om te innoveren.</p>
			<p>Het volgende kabinet moet zich realiseren dat innovatie cruciaal is voor economische groei. Dus reserveer alvast 200 miljoen euro per jaar, voor het komende decennium. Definieer Nederlandse doelen die even ambitieus als urgent zijn. Bijvoorbeeld landbouw die de natuur versterkt in plaats van uitput. Of energie die bijna gratis is. Als we dit goed doen, dan wordt weer duidelijk voor Nederlanders waar we, behalve dijken bouwen, goed in zijn en kunnen we Nederlanders leren groot te denken.</p>
		</MoonshotLayout>
	);
};

export default MoonshotNadi;
